import{solveZip,wallKey}from'./solver.js';
function xmur3(str){let h=1779033703^str.length;for(let i=0;i<str.length;i++){h=Math.imul(h^str.charCodeAt(i),3432918353);h=h<<13|h>>>19;}return()=>{h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return(h^=h>>>16)>>>0;};}
function mulberry32(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
const randomFor=seed=>mulberry32(xmur3(String(seed))());
function shuffle(items,random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function openNeighbors(rows,cols,i){const r=Math.floor(i/cols),c=i%cols,out=[];if(r>0)out.push(i-cols);if(r+1<rows)out.push(i+cols);if(c>0)out.push(i-1);if(c+1<cols)out.push(i+1);return out;}
function snakePath(rows,cols,random){const path=[];const byRows=random()<.5;if(byRows){for(let r=0;r<rows;r++){const colsOrder=[...Array(cols).keys()];if(r%2)colsOrder.reverse();for(const c of colsOrder)path.push(r*cols+c);}}else{for(let c=0;c<cols;c++){const rowsOrder=[...Array(rows).keys()];if(c%2)rowsOrder.reverse();for(const r of rowsOrder)path.push(r*cols+c);}}if(random()<.5)path.reverse();return path;}
function randomHamiltonian(rows,cols,random,maxNodes=120000){const N=rows*cols;const starts=shuffle([...Array(N).keys()],random);for(const start of starts.slice(0,Math.min(N,12))){const visited=new Uint8Array(N),path=[start];visited[start]=1;let nodes=0;function connectedFrom(head){const seen=new Uint8Array(N),stack=[head];seen[head]=1;let count=1;while(stack.length){const u=stack.pop();for(const v of openNeighbors(rows,cols,u))if(!visited[v]&&!seen[v]){seen[v]=1;count++;stack.push(v);}}return count===N-path.length;}function dfs(cur){if(++nodes>maxNodes)return false;if(path.length===N)return true;let moves=openNeighbors(rows,cols,cur).filter(v=>!visited[v]);moves=shuffle(moves,random).sort((a,b)=>openNeighbors(rows,cols,a).reduce((s,v)=>s+(!visited[v]?1:0),0)-openNeighbors(rows,cols,b).reduce((s,v)=>s+(!visited[v]?1:0),0));for(const v of moves){visited[v]=1;path.push(v);if(path.length===N||connectedFrom(v)){if(dfs(v))return true;}path.pop();visited[v]=0;}return false;}if(dfs(start))return path.slice();}return snakePath(rows,cols,random);}
const CONFIG={easy:{rows:5,cols:5,waypoints:9,targetWalls:5},medium:{rows:6,cols:6,waypoints:9,targetWalls:5},hard:{rows:6,cols:6,waypoints:7,targetWalls:3},challenge:{rows:7,cols:7,waypoints:8,targetWalls:4}};
function chooseWaypoints(path,count,random){const N=path.length,K=Math.max(2,Math.min(count,N));const positions=[0];for(let k=1;k<K-1;k++){const ideal=k*(N-1)/(K-1),span=Math.max(1,Math.floor((N-1)/(K-1)*.28));const lo=Math.max(positions.at(-1)+1,Math.floor(ideal-span));const hi=Math.min(N-(K-k),Math.ceil(ideal+span));positions.push(lo+Math.floor(random()*(hi-lo+1)));}positions.push(N-1);return positions.map(i=>path[i]);}
function allNonPathWalls(rows,cols,path){const used=new Set();for(let i=1;i<path.length;i++)used.add(wallKey(path[i-1],path[i]));const walls=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const i=r*cols+c;if(c+1<cols&&!used.has(wallKey(i,i+1)))walls.push(wallKey(i,i+1));if(r+1<rows&&!used.has(wallKey(i,i+cols)))walls.push(wallKey(i,i+cols));}return walls;}
export function generateZip({seed,difficulty='medium'}={}){const cfg=CONFIG[difficulty]||CONFIG.medium;const random=randomFor(seed);const solution=randomHamiltonian(cfg.rows,cfg.cols,random);const waypoints=chooseWaypoints(solution,cfg.waypoints,random);let walls=allNonPathWalls(cfg.rows,cfg.cols,solution);for(const wall of shuffle(walls,random)){if(walls.length<=cfg.targetWalls)break;const candidate=walls.filter(w=>w!==wall);const puzzle={rows:cfg.rows,cols:cfg.cols,waypoints,walls:candidate,seed,difficulty};const check=solveZip(puzzle,{limit:2,maxNodes:difficulty==='challenge'?180000:120000});if(!check.aborted&&check.solutions.length===1)walls=candidate;}const puzzle={rows:cfg.rows,cols:cfg.cols,waypoints,walls,seed,difficulty};const check=solveZip(puzzle,{limit:2,maxNodes:250000});if(check.aborted||check.solutions.length!==1)throw new Error(`Zip generator failed uniqueness: ${difficulty}`);return{puzzle,solution:check.solutions[0],difficultyScore:check.nodes};}
