import{currentDateKey}from'../daily.js';
import{getDailyGame}from'../services/daily-service.js';
import{completeGame}from'../services/progress-service.js';
import{getIdentity}from'../services/identity-service.js';
import{track}from'../services/analytics-service.js';
import{loadFigloState}from'../storage.js';
import{requestedGameMode,setGameMode}from'../ui/game-mode.js';
import{showGameLoader,hideGameLoader}from'../ui/game-loader.js';
import{generateZipAsync}from'./generator-async.js';
import{applyPathCell,isSolvedPath,longestSolutionPrefix,isSolutionPrefix}from'./rules.js';
import{createZipSession,loadZipSession,saveZipSession,clearZipSession}from'./session.js';
import{wallKey}from'./solver.js';

const $=s=>document.querySelector(s),boardEl=$('#board'),today=currentDateKey(),identity=getIdentity(),requestedMode=requestedGameMode();
const isLocalTest=location.hostname==='localhost'||location.hostname==='127.0.0.1';
let record=null,puzzle=null,solution=null,session=null,gameMode='daily',trainingNumber=0,timerTick=null,hintTarget=null,dragging=false,pointerId=null,gestureBefore=null,lastPointerCell=null,feedbackTimer=null;
function formatMs(ms){const sec=Math.floor(Math.max(0,ms)/1000);return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function elapsedNow(){return!session?0:session.elapsedMs+(session.runningSince?Date.now()-session.runningSince:0);}
function renderTimer(){$('#timer').textContent=formatMs(elapsedNow());}
function save(){if(session&&gameMode==='daily')saveZipSession(session);}
function ensureTimerStarted(){if(!session||session.finished)return;if(!session.runningSince){session.runningSince=Date.now();session.startedAt||=new Date().toISOString();track('game_started',{gameId:'zip',puzzleId:record?.puzzleId,date:today,mode:gameMode,localId:identity.localId});save();}timerTick||=setInterval(renderTimer,250);}
function pauseTimer(){if(!session?.runningSince)return;session.elapsedMs+=Date.now()-session.runningSince;session.runningSince=null;if(timerTick)clearInterval(timerTick);timerTick=null;save();renderTimer();}
function randomSeed(){return globalThis.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;}
function dailyBest(){return loadFigloState(today).games.zip?.bestTimeMs||null;}
function setFeedback(copy,type=''){const el=$('#feedback');el.textContent=copy;el.className=`feedback${type?` ${type}`:''}`;if(feedbackTimer)clearTimeout(feedbackTimer);if(type==='error')feedbackTimer=setTimeout(()=>{if(session&&!session.finished){el.textContent='Połącz liczby po kolei i wypełnij każde pole.';el.className='feedback';}},1800);}
function checkpointMap(){return new Map((puzzle?.waypoints||[]).map((cell,index)=>[cell,index+1]));}
function buildBoard(){boardEl.innerHTML='';boardEl.style.setProperty('--cols',String(puzzle.cols));boardEl.style.setProperty('--rows',String(puzzle.rows));boardEl.setAttribute('aria-label',`Plansza Zip ${puzzle.rows} na ${puzzle.cols}`);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('zip-path-layer');svg.setAttribute('viewBox',`0 0 ${puzzle.cols} ${puzzle.rows}`);svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.id='zipPathLine';svg.appendChild(line);boardEl.appendChild(svg);const walls=new Set(puzzle.walls||[]),numbers=checkpointMap(),N=puzzle.rows*puzzle.cols;for(let index=0;index<N;index++){const row=Math.floor(index/puzzle.cols),col=index%puzzle.cols,cell=document.createElement('button');cell.type='button';cell.className='zip-cell';cell.dataset.index=String(index);cell.setAttribute('role','gridcell');if(col+1<puzzle.cols&&walls.has(wallKey(index,index+1)))cell.classList.add('wall-r');if(row+1<puzzle.rows&&walls.has(wallKey(index,index+puzzle.cols)))cell.classList.add('wall-b');const number=numbers.get(index);if(number){cell.classList.add('numbered');cell.innerHTML=`<span class="checkpoint">${number}</span>`;cell.setAttribute('aria-label',`Pole ${row+1}, ${col+1}, liczba ${number}`);}else cell.setAttribute('aria-label',`Pole ${row+1}, ${col+1}`);boardEl.appendChild(cell);}}
function pathPoints(){return(session.path||[]).map(index=>`${index%puzzle.cols+.5},${Math.floor(index/puzzle.cols)+.5}`).join(' ');}
function renderBoard(){if(!puzzle||!session)return;const cells=boardEl.querySelectorAll('.zip-cell'),pathSet=new Set(session.path);cells.forEach((cell,index)=>{cell.classList.toggle('on-path',pathSet.has(index));cell.classList.toggle('path-head',session.path.at(-1)===index);cell.classList.toggle('hint-target',hintTarget===index);});const line=$('#zipPathLine');if(line)line.setAttribute('points',pathPoints());$('#filledCounter').textContent=`${session.path.length}/${puzzle.rows*puzzle.cols}`;renderTimer();updateButtons();}
function updateButtons(){const disabled=!session?.history?.length||session.finished;$('#undo').disabled=disabled;$('#mobileUndo').disabled=disabled;$('#hint').disabled=session.finished;$('#mobileHint').disabled=session.finished;}
function clearHint(){hintTarget=null;$('#hintCard').hidden=true;renderBoard();}
function pathsEqual(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i]);}
function applyCell(index){if(session.finished)return false;const result=applyPathCell(puzzle,session.path,index);if(!result.ok){setFeedback(result.reason,'error');return false;}if(pathsEqual(result.path,session.path))return false;ensureTimerStarted();hintTarget=null;$('#hintCard').hidden=true;session.path=result.path;save();renderBoard();if(isSolvedPath(puzzle,session.path))finish();return true;}
function cellFromPoint(x,y){const cell=document.elementFromPoint(x,y)?.closest?.('.zip-cell');return cell&&boardEl.contains(cell)?Number(cell.dataset.index):null;}
function onPointerDown(event){if(session.finished)return;const cell=event.target.closest('.zip-cell');if(!cell)return;event.preventDefault();dragging=true;pointerId=event.pointerId;gestureBefore=[...session.path];lastPointerCell=Number(cell.dataset.index);boardEl.setPointerCapture?.(pointerId);applyCell(lastPointerCell);}
function onPointerMove(event){if(!dragging||event.pointerId!==pointerId||session.finished)return;const index=cellFromPoint(event.clientX,event.clientY);if(index===null||index===lastPointerCell)return;lastPointerCell=index;applyCell(index);}
function finishGesture(event){if(!dragging||event.pointerId!==pointerId)return;dragging=false;boardEl.releasePointerCapture?.(pointerId);pointerId=null;lastPointerCell=null;if(gestureBefore&&!pathsEqual(gestureBefore,session.path)&&!session.finished){session.history.push(gestureBefore);if(session.history.length>100)session.history.shift();save();updateButtons();}gestureBefore=null;}
function undo(){if(!session.history.length||session.finished)return;hintTarget=null;$('#hintCard').hidden=true;session.path=session.history.pop();save();renderBoard();setFeedback('Cofnięto ostatni ruch.');}
function reset(){if(session.finished)return;hintTarget=null;$('#hintCard').hidden=true;session.path=[];session.history=[];session.elapsedMs=0;session.runningSince=null;session.startedAt=null;if(timerTick)clearInterval(timerTick);timerTick=null;save();renderBoard();setFeedback('Plansza wyczyszczona. Zacznij od 1.');}
function revealHintCard(){const card=$('#hintCard');if(matchMedia('(max-width: 767px)').matches)requestAnimationFrame(()=>requestAnimationFrame(()=>card.scrollIntoView({behavior:'smooth',block:'center'})));}
function showHint(){if(session.finished)return;const common=longestSolutionPrefix(session.path,solution);if(common<session.path.length){session.path=session.path.slice(0,common);session.history=session.history.filter(path=>isSolutionPrefix(path,solution)&&path.length<=common);hintTarget=null;save();renderBoard();setFeedback('Cofnięto do ostatniego poprawnego miejsca. Podpowiedź nie została wykorzystana.');return;}hintTarget=solution[session.path.length]??null;const card=$('#hintCard');card.hidden=false;session.hintsUsed=(session.hintsUsed||0)+1;save();track('hint_used',{gameId:'zip',puzzleId:record?.puzzleId,date:today,mode:gameMode,localId:identity.localId});$('#hintText').textContent=session.path.length?'Następny poprawny krok jest podświetlony na planszy.':'Zacznij od pola 1 — jest podświetlone na planszy.';renderBoard();revealHintCard();}
function exposeTestHook(){if(isLocalTest&&solution)globalThis.__ZIP_TEST__={getSolution:()=>[...solution],getPuzzle:()=>JSON.parse(JSON.stringify(puzzle))};}
function finish(){session.finished=true;pauseTimer();const ms=session.elapsedMs;let best=dailyBest();if(gameMode==='daily'){save();const result=completeGame({gameId:'zip',puzzleId:record.puzzleId,date:today,elapsedMs:ms,mode:'daily',startedAt:session.startedAt||null});best=result.state.games.zip?.bestTimeMs||ms;track('game_completed',{...result.event,localId:identity.localId,hintsUsed:session.hintsUsed||0});$('#doneCopy').textContent=result.firstDayCompletionToday?'Dzisiejszy zestaw ukończony!':'Zip zaliczony. Zostały kolejne gry z zestawu.';}else{track('game_completed',{gameId:'zip',puzzleId:record.puzzleId,date:today,elapsedMs:ms,mode:'training',localId:identity.localId,hintsUsed:session.hintsUsed||0});$('#doneCopy').textContent='Trening ukończony. Ten wynik nie wpływa na dzisiejszy zestaw.';}$('#finalTime').textContent=formatMs(ms);$('#bestTime').textContent=best?formatMs(best):'—';$('#done').hidden=false;$('#replay').focus();renderBoard();setFeedback('Zip ukończony!','success');}
async function loadTraining(){pauseTimer();showGameLoader('Przygotowuję planszę treningową…');boardEl.setAttribute('aria-busy','true');try{const seed=randomSeed(),generated=await generateZipAsync({seed,difficulty:'medium'});puzzle=generated.puzzle;solution=generated.solution;record={puzzleId:`zip-training:${seed}`,puzzle,solution};session=createZipSession({date:today,seed:record.puzzleId});gameMode='training';setGameMode('training');trainingNumber+=1;$('#roundLabel').textContent=`Trening #${trainingNumber}`;$('#done').hidden=true;$('#hintCard').hidden=true;buildBoard();exposeTestHook();renderBoard();setFeedback('Zacznij od 1 i poprowadź jedną linię przez całą planszę.');track('game_training_started',{gameId:'zip',puzzleId:record.puzzleId,date:today,localId:identity.localId});}catch(error){console.error('zip training generation failure',error);$('#loadError').hidden=false;throw error;}finally{boardEl.removeAttribute('aria-busy');hideGameLoader();}}
async function loadDaily(){showGameLoader('Przygotowuję dzisiejszy Zip…');boardEl.setAttribute('aria-busy','true');gameMode='daily';setGameMode('daily');$('#roundLabel').textContent='Dzisiaj';$('#done').hidden=true;try{record=await getDailyGame('zip',today);puzzle=record.puzzle;solution=record.solution;session=loadZipSession({date:today,seed:record.puzzleId});if(session.finished){clearZipSession();session=createZipSession({date:today,seed:record.puzzleId});}if(session.runningSince)timerTick=setInterval(renderTimer,250);buildBoard();exposeTestHook();renderBoard();setFeedback('Zacznij od 1 i połącz wszystkie liczby po kolei.');track('game_opened',{gameId:'zip',puzzleId:record.puzzleId,date:today,mode:'daily',localId:identity.localId});}catch(error){console.error('zip daily load failure',error);$('#loadError').hidden=false;}finally{boardEl.removeAttribute('aria-busy');hideGameLoader();}}
async function start(){const state=loadFigloState(today);if(requestedMode==='training'||state.daily.completedGames.includes('zip')||!state.daily.requiredGames.includes('zip'))await loadTraining();else await loadDaily();}
boardEl.addEventListener('pointerdown',onPointerDown);boardEl.addEventListener('pointermove',onPointerMove);boardEl.addEventListener('pointerup',finishGesture);boardEl.addEventListener('pointercancel',finishGesture);$('#undo').addEventListener('click',undo);$('#mobileUndo').addEventListener('click',undo);$('#hint').addEventListener('click',showHint);$('#mobileHint').addEventListener('click',showHint);$('#reset').addEventListener('click',reset);$('#mobileReset').addEventListener('click',reset);$('#hintClose').addEventListener('click',clearHint);$('#rulesTop').addEventListener('click',()=>{$('#rules').open=true;$('#rules').scrollIntoView({behavior:'smooth'});});$('#replay').addEventListener('click',()=>loadTraining().catch(()=>{}));document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseTimer();else if(gameMode==='daily'&&session&&!session.finished&&session.path.length){session.runningSince=Date.now();save();timerTick||=setInterval(renderTimer,250);}});window.addEventListener('pagehide',pauseTimer);start();
