import { test, expect } from '@playwright/test';

const STORAGE_KEY='figlo_user_state_v2';
const DATE_A='2026-08-21';
const DATE_B='2026-08-22';
const DATE_GAP='2026-08-23';
const seconds=value=>{const [m,s]=String(value).split(':').map(Number);return m*60+s;};
async function waitForCrownReady(page){await expect(page.locator('#board .cell')).toHaveCount(81);await page.waitForFunction(()=>Array.isArray(window.__FIGLO_TEST__?.getSolution?.())&&window.__FIGLO_TEST__.getSolution().length===9);await expect(page.locator('#gameLoader')).toBeHidden();}
async function fresh(page,path=`/index.html?date=${DATE_A}`){await page.goto(path);await page.evaluate(()=>localStorage.clear());await page.reload();if(path.includes('korony.html'))await waitForCrownReady(page);}
async function solveDaily(page){await waitForCrownReady(page);const solution=await page.evaluate(()=>window.__FIGLO_TEST__.getSolution());expect(solution).toHaveLength(9);for(const index of solution){const cell=page.locator('#board .cell').nth(index);await cell.click();await cell.click();}await expect(page.locator('#done')).toBeVisible();}
const isMobile=info=>info.project.name==='mobile-chromium';

test('fresh pre-Duet user sees incomplete Crown daily',async({page})=>{await fresh(page);await expect(page.locator('#progressRing')).toHaveText('0/1');await expect(page.locator('#statStreak')).toHaveText('0');});
test('fresh Crown Daily opens playable board without completion modal',async({page})=>{await fresh(page,`/korony.html?date=${DATE_A}`);await expect(page.locator('#done')).toBeHidden();await expect(page.locator('#roundLabel')).toHaveText('Dzisiaj');});
test('Crown move and undo history survive reload',async({page},info)=>{await fresh(page,`/korony.html?date=${DATE_A}`);const cells=page.locator('#board .cell');await cells.nth(0).click();await cells.nth(1).click();await page.reload();await waitForCrownReady(page);await expect(page.locator('#board .cell').nth(0)).toHaveAttribute('aria-label',/X/);const undo=isMobile(info)?page.locator('#mobileUndo'):page.locator('#undo');await undo.click();await expect(page.locator('#board .cell').nth(1)).toHaveAttribute('aria-label',/puste/);});
test('Crown Auto-X persists',async({page},info)=>{await fresh(page,`/korony.html?date=${DATE_A}`);if(isMobile(info)){await page.locator('#mobileAutoX').click();await page.reload();await waitForCrownReady(page);await expect(page.locator('#mobileAutoX')).toHaveAttribute('aria-pressed','true');}else{await page.locator('#autoX').check();await page.reload();await waitForCrownReady(page);await expect(page.locator('#autoX')).toBeChecked();}});
test('Crown timer survives reload',async({page})=>{await fresh(page,`/korony.html?date=${DATE_A}`);await page.locator('#board .cell').nth(0).click();await page.waitForTimeout(1200);const before=await page.locator('#timer').textContent();await page.reload();await waitForCrownReady(page);const after=await page.locator('#timer').textContent();expect(after).not.toBe('00:00');expect(seconds(after)).toBeGreaterThanOrEqual(Math.max(1,seconds(before)-1));});
test('Crown hint highlight is cleared by the next move',async({page},info)=>{await fresh(page,`/korony.html?date=${DATE_A}`);const hint=isMobile(info)?page.locator('#mobileHint'):page.locator('#hint');await hint.click();await expect(page.locator('#hintCard')).toHaveClass(/show/);expect(await page.locator('#board .hint-area, #board .hint-focus, #board .hint-candidate, #board .hint-eliminate').count()).toBeGreaterThan(0);await page.locator('#board .cell').first().click();await expect(page.locator('#hintCard')).not.toHaveClass(/show/);await expect(page.locator('#board .hint-area, #board .hint-focus, #board .hint-candidate, #board .hint-eliminate')).toHaveCount(0);});
test('Crown daily completes pre-launch day and later entry starts training without increment',async({page})=>{await fresh(page,`/korony.html?date=${DATE_A}`);await solveDaily(page);const first=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),STORAGE_KEY);expect(first.user.streak).toBe(1);await page.goto(`/index.html?date=${DATE_A}`);await expect(page.locator('#progressRing')).toHaveText('1/1');await expect(page.locator('#crownsCard')).toHaveAttribute('href',/mode=training/);await page.goto(`/korony.html?date=${DATE_A}`);await waitForCrownReady(page);await expect(page.locator('#roundLabel')).toContainText(/Trening/i);await expect(page.locator('#done')).toBeHidden();await solveDaily(page);const second=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),STORAGE_KEY);expect(second.user.completedGames).toBe(first.user.completedGames);});
test('consecutive pre-launch Crown days extend streak',async({page})=>{await fresh(page,`/korony.html?date=${DATE_A}`);await solveDaily(page);await page.goto(`/korony.html?date=${DATE_B}`);await solveDaily(page);await page.goto(`/index.html?date=${DATE_B}`);await expect(page.locator('#statStreak')).toHaveText('2');});
test('pre-launch missing day resets streak',async({page})=>{await fresh(page,`/korony.html?date=${DATE_A}`);await solveDaily(page);await page.goto(`/korony.html?date=${DATE_GAP}`);await solveDaily(page);await page.goto(`/index.html?date=${DATE_GAP}`);await expect(page.locator('#statStreak')).toHaveText('1');});
test('corrupted storage falls back',async({page})=>{await page.goto(`/index.html?date=${DATE_A}`);await page.evaluate(k=>localStorage.setItem(k,'{broken-json'),STORAGE_KEY);await page.reload();await expect(page.locator('#progressRing')).toHaveText('0/1');});
test('Crown board fits viewport',async({page},info)=>{await fresh(page,`/korony.html?date=${DATE_A}`);const box=await page.locator('#board').boundingBox();const viewport=page.viewportSize();expect(box.x+box.width).toBeLessThanOrEqual(viewport.width+1);if(isMobile(info))await expect(page.locator('.mobile-controls')).toBeVisible();});
