import test from 'node:test';
import assert from 'node:assert/strict';
class LocalStorageMock { constructor(){this.map=new Map();} getItem(k){return this.map.has(k)?this.map.get(k):null;} setItem(k,v){this.map.set(k,String(v));} removeItem(k){this.map.delete(k);} clear(){this.map.clear();} }
globalThis.localStorage=new LocalStorageMock();
const storage=await import('../src/storage.js');
const progress=await import('../src/services/progress-service.js');
const {requiredGamesForDate}=await import('../src/daily-games.js');
const {STORAGE_KEY,isTodayComplete,loadFigloState,updateFigloSettings}=storage;
const resetStorage=()=>localStorage.clear();
const complete=(game,date,timeMs=60000)=>progress.completeGame({gameId:game,puzzleId:`${game}:${date}:v1`,date,elapsedMs:timeMs,mode:'daily'});
function completeDay(date,order=requiredGamesForDate(date)){let result;for(const game of order)result=complete(game,date);return result;}
test('Duet launch state starts with two required games',()=>{resetStorage();const state=loadFigloState('2026-08-24');assert.deepEqual(state.daily.requiredGames,['korony','duet']);assert.deepEqual(state.daily.completedGames,[]);assert.equal(isTodayComplete(state),false);});
test('first game gives 1/2 and does not grow streak',()=>{resetStorage();const result=complete('korony','2026-08-24',120000);assert.equal(result.firstGameCompletionToday,true);assert.equal(result.firstDayCompletionToday,false);assert.equal(result.state.user.streak,0);assert.equal(result.state.user.completedDays,0);assert.equal(result.state.user.completedGames,1);assert.deepEqual(result.state.daily.completedGames,['korony']);assert.equal(isTodayComplete(result.state),false);});
test('second different game completes 2/2 before Bloki launch',()=>{resetStorage();complete('korony','2026-08-24',120000);const result=complete('duet','2026-08-24',90000);assert.equal(result.firstDayCompletionToday,true);assert.equal(result.state.user.streak,1);assert.equal(result.state.user.completedDays,1);assert.equal(result.state.user.completedGames,2);assert.equal(result.state.games.duet.completedCount,1);assert.equal(isTodayComplete(result.state),true);});
test('Bloki launch requires 3/3 for a completed day',()=>{resetStorage();complete('korony','2026-08-25');complete('duet','2026-08-25');let state=loadFigloState('2026-08-25');assert.deepEqual(state.daily.requiredGames,['korony','duet','bloki']);assert.equal(isTodayComplete(state),false);const result=complete('bloki','2026-08-25');assert.equal(result.firstDayCompletionToday,true);assert.equal(result.state.user.streak,1);assert.equal(result.state.games.bloki.completedCount,1);assert.equal(isTodayComplete(result.state),true);});
test('Latarnie launch requires 4/4 and persists game stats',()=>{resetStorage();complete('korony','2026-08-26');complete('duet','2026-08-26');complete('bloki','2026-08-26');let state=loadFigloState('2026-08-26');assert.deepEqual(state.daily.requiredGames,['korony','duet','bloki','latarnie']);assert.equal(isTodayComplete(state),false);assert.ok(state.games.latarnie);const result=complete('latarnie','2026-08-26',75000);assert.equal(result.firstDayCompletionToday,true);assert.equal(result.state.games.latarnie.completedCount,1);assert.equal(result.state.games.latarnie.bestTimeMs,75000);assert.equal(isTodayComplete(result.state),true);});
test('replays do not increment counters or improve daily best time',()=>{resetStorage();completeDay('2026-08-24');const before=loadFigloState('2026-08-24');complete('duet','2026-08-24',30000);complete('korony','2026-08-24',30000);const after=loadFigloState('2026-08-24');assert.equal(after.user.streak,before.user.streak);assert.equal(after.user.completedDays,before.user.completedDays);assert.equal(after.user.completedGames,before.user.completedGames);assert.equal(after.games.duet.bestTimeMs,60000);assert.equal(after.games.korony.bestTimeMs,60000);});
test('training completion never mutates Daily progress or stats',()=>{resetStorage();const before=loadFigloState('2026-08-25');const result=progress.completeGame({gameId:'korony',puzzleId:'training-1',date:'2026-08-25',elapsedMs:15000,mode:'training'});const after=loadFigloState('2026-08-25');assert.deepEqual(after.daily.completedGames,before.daily.completedGames);assert.equal(after.user.completedGames,before.user.completedGames);assert.equal(after.games.korony.completedCount,before.games.korony.completedCount);assert.equal(after.games.korony.bestTimeMs,before.games.korony.bestTimeMs);assert.equal(result.firstGameCompletionToday,false);assert.equal(result.firstDayCompletionToday,false);});
test('consecutive full days increase streak only after all required games',()=>{resetStorage();completeDay('2026-08-24');complete('korony','2026-08-25');complete('duet','2026-08-25');let mid=loadFigloState('2026-08-25');assert.equal(mid.user.streak,1);const end=complete('bloki','2026-08-25');assert.equal(end.state.user.streak,2);assert.deepEqual(end.state.user.completedDates,['2026-08-24','2026-08-25']);});
test('skipping a day resets streak after next full set',()=>{resetStorage();completeDay('2026-08-24');const result=completeDay('2026-08-26');assert.equal(result.state.user.streak,1);assert.equal(result.state.user.completedDays,2);});
test('new date resets daily progress and switches to three games',()=>{resetStorage();completeDay('2026-08-24');const next=loadFigloState('2026-08-25');assert.deepEqual(next.daily.completedGames,[]);assert.deepEqual(next.daily.requiredGames,['korony','duet','bloki']);assert.equal(next.user.streak,1);assert.equal(next.user.completedDays,1);assert.equal(next.user.completedGames,2);});
test('dates before Duet launch remain Korony-only',()=>{resetStorage();const state=loadFigloState('2026-08-23');assert.deepEqual(state.daily.requiredGames,['korony']);const result=complete('korony','2026-08-23');assert.equal(result.firstDayCompletionToday,true);assert.equal(result.state.user.streak,1);});
test('Auto-X setting persists in unified storage',()=>{resetStorage();updateFigloSettings({autoX:true});const state=loadFigloState('2026-08-24');assert.equal(state.settings.autoX,true);assert.ok(localStorage.getItem(STORAGE_KEY));});
