import{createPuzzle,indexOf,orthogonalNeighbors}from'./model.js';
import{solveLatarnie,hasUniqueSolution}from'./solver.js';
import{humanSolve}from'./human-solver.js';
function xmur3(str){let h=1779033703^str.length;for(let i=0;i<str.length;i++){h=Math.imul(h^str.charCodeAt(i),3432918353);h=h<<13|h>>>19;}return()=>{h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return(h^=h>>>16)>>>0;};}
function mulberry32(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function randomFor(seed){return mulberry32(xmur3(String(seed))());}
function shuffle(items,random){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
const CONFIG={easy:{rows:7,cols:7,wallRate:.32,retain:.92},medium:{rows:7,cols:7,wallRate:.29,retain:.75},hard:{rows:8,cols:8,wallRate:.27,retain:.58},challenge:{rows:8,cols:8,wallRate:.25,retain:.45}};
function randomWalls(config,random){const walls=[];for(let r=0;r<config.rows;r++)for(let c=0;c<config.cols;c++)if(random()<config.wallRate)walls.push({index:indexOf(r,c,config.cols),clue:null});return walls;}
function numberWalls(puzzle,solution){const bulbs=new Set(solution);return puzzle.walls.map(wall=>({...wall,clue:orthogonalNeighbors(wall.index,puzzle).filter(i=>bulbs.has(i)).length}));}
function removeClues(puzzle,retain,random){let current={...puzzle,walls:puzzle.walls.map(w=>({...w}))};const target=Math.max(1,Math.ceil(current.walls.length*retain));for(const index of shuffle(current.walls.map(w=>w.index),random)){const numbered=current.walls.filter(w=>Number.isInteger(w.clue)).length;if(numbered<=target)break;const next={...current,walls:current.walls.map(w=>w.index===index?{...w,clue:null}:{...w})};if(hasUniqueSolution(next))current=next;}return current;}
export function generateLatarnie({seed,difficulty='medium',maxAttempts=180}={}){const config=CONFIG[difficulty]||CONFIG.medium;for(let attempt=0;attempt<maxAttempts;attempt++){const random=randomFor(`${seed}:${attempt}`);const base=createPuzzle({rows:config.rows,cols:config.cols,walls:randomWalls(config,random),seed,difficulty});if(base.walls.length<5)continue;const baseSolution=solveLatarnie(base,{limit:1})[0];if(!baseSolution)continue;const numbered={...base,walls:numberWalls(base,baseSolution)};if(!hasUniqueSolution(numbered))continue;const puzzle=removeClues(numbered,config.retain,random);const solutions=solveLatarnie(puzzle,{limit:2});if(solutions.length!==1)continue;const human=humanSolve(puzzle);return{puzzle,solution:solutions[0],difficultyScore:human.score};}throw new Error(`Nie udało się wygenerować Latarni: ${difficulty}`);}
