import{orthogonalNeighbors,whiteCells}from'./model.js';
import{lightSourcesFor,visibleFrom,litCells}from'./rules.js';
import{solveLatarnie}from'./solver.js';

function baseSolution(puzzle){const solutions=solveLatarnie(puzzle,{limit:1});return solutions.length?new Set(solutions[0]):null;}
function stepKeepsSolution(puzzle,bulbs,noBulbs,step){const nextBulbs=new Set(bulbs),nextNoBulbs=new Set(noBulbs);if(step.value===1){nextNoBulbs.delete(step.index);nextBulbs.add(step.index);}else{nextBulbs.delete(step.index);nextNoBulbs.add(step.index);}return solveLatarnie(puzzle,{limit:1,initialBulbs:[...nextBulbs],initialNoBulbs:[...nextNoBulbs]}).length>0;}
function correctionStep(puzzle,bulbs,noBulbs){const solution=baseSolution(puzzle);if(!solution)return null;for(const index of bulbs)if(!solution.has(index))return{kind:'wrong-bulb',index,value:0,reason:'Ta latarnia jest błędna. Usuń ją i spróbuj ponownie.',area:[index],indices:[index]};for(const index of noBulbs)if(solution.has(index))return{kind:'wrong-cross',index,value:1,reason:'Ten X jest błędny. Usuń go — w tym polu musi stanąć latarnia.',area:[index],indices:[index]};return null;}
function wallCells(puzzle,wall){const walls=new Set((puzzle.walls||[]).map(w=>w.index));return orthogonalNeighbors(wall.index,puzzle).filter(index=>!walls.has(index));}
function candidateGroups(puzzle,bulbs,noBulbs){const forcedBulbs=[],onlySources=[],zeroClues=[],completedClues=[],visibility=[];
for(const wall of puzzle.walls||[]){if(!Number.isInteger(wall.clue))continue;const cells=wallCells(puzzle,wall),placed=cells.filter(i=>bulbs.has(i)),available=cells.filter(i=>!bulbs.has(i)&&!noBulbs.has(i));
if(placed.length+available.length===wall.clue&&available.length){for(const index of available)forcedBulbs.push({kind:'clue-forced',index,value:1,reason:available.length===1?`Do liczby ${wall.clue} brakuje dokładnie tej latarni. Wstaw ją w zaznaczone pole.`:`Żeby spełnić liczbę ${wall.clue}, wszystkie zaznaczone pola muszą zawierać latarnie.`,area:[wall.index,...cells],indices:[...available]});}
if(wall.clue===0&&available.length){for(const index of available)zeroClues.push({kind:'zero-clue',index,value:0,reason:'Przy liczbie 0 żadne sąsiednie pole nie może zawierać latarni. Oznacz zaznaczone pola jako X.',area:[wall.index,...cells],indices:[...available]});continue;}
if(placed.length===wall.clue&&available.length){for(const index of available)completedClues.push({kind:'clue-complete',index,value:0,reason:available.length===1?`Przy ${wall.clue} stoi już komplet latarni. Oznacz zaznaczone pole jako X.`:`Przy ${wall.clue} stoi już komplet latarni. Oznacz pozostałe zaznaczone pola jako X.`,area:[wall.index,...cells],indices:[...available]});}}
const lit=litCells(puzzle,bulbs);for(const cell of whiteCells(puzzle)){if(lit.has(cell))continue;const possible=lightSourcesFor(cell,puzzle).filter(source=>!noBulbs.has(source));if(possible.length===1)onlySources.push({kind:'only-light-source',index:possible[0],value:1,reason:'To nieoświetlone pole ma tylko jedno możliwe źródło światła. Wstaw latarnię w zaznaczone miejsce.',area:[cell,possible[0]],indices:[possible[0]]});}
for(const bulb of bulbs)for(const cell of visibleFrom(bulb,puzzle))if(!bulbs.has(cell)&&!noBulbs.has(cell))visibility.push({kind:'visibility',index:cell,value:0,reason:'To pole jest już w linii światła istniejącej latarni. Oznacz je jako X.',area:[bulb,cell],indices:[cell]});
return{forcedBulbs,onlySources,zeroClues,completedClues,visibility};}
function firstSafeStep(puzzle,bulbs,noBulbs,groups){for(const group of groups)for(const step of group)if(stepKeepsSolution(puzzle,bulbs,noBulbs,step))return step;return null;}
export function nextHumanStep(puzzle,{bulbs=new Set(),noBulbs=new Set()}={}){const correction=correctionStep(puzzle,bulbs,noBulbs);if(correction)return correction;const groups=candidateGroups(puzzle,bulbs,noBulbs);const localBulb=firstSafeStep(puzzle,bulbs,noBulbs,[groups.forcedBulbs,groups.onlySources]);if(localBulb)return localBulb;const solution=baseSolution(puzzle);if(!solution)return null;for(const index of solution)if(!bulbs.has(index)&&!noBulbs.has(index))return{kind:'solver-forced',index,value:1,reason:'Po uwzględnieniu całej planszy tutaj na pewno musi stanąć latarnia. Wstaw ją w zaznaczone pole.',area:[index],indices:[index]};const cleanup=firstSafeStep(puzzle,bulbs,noBulbs,[groups.zeroClues,groups.completedClues,groups.visibility]);if(cleanup)return cleanup;for(const index of whiteCells(puzzle))if(!solution.has(index)&&!bulbs.has(index)&&!noBulbs.has(index))return{kind:'solver-excluded',index,value:0,reason:'Tutaj na pewno nie może stać latarnia. Oznacz zaznaczone pole jako X.',area:[index],indices:[index]};return null;}
export function humanSolve(puzzle){const bulbs=new Set(),noBulbs=new Set(),steps=[];const scoring={'zero-clue':1,visibility:1,'clue-complete':1,'clue-forced':2,'only-light-source':4,'solver-forced':6,'solver-excluded':6};for(let i=0;i<puzzle.rows*puzzle.cols*8;i++){const step=nextHumanStep(puzzle,{bulbs,noBulbs});if(!step||step.kind==='wrong-bulb'||step.kind==='wrong-cross')break;steps.push(step);if(step.value===1)bulbs.add(step.index);else noBulbs.add(step.index);}return{bulbs,noBulbs,steps,score:steps.reduce((s,x)=>s+(scoring[x.kind]||1),0)};}
