import{orthogonalNeighbors,whiteCells}from'./model.js';
import{lightSourcesFor,visibleFrom,litCells}from'./rules.js';
import{solveLatarnie}from'./solver.js';

function baseSolution(puzzle){const solutions=solveLatarnie(puzzle,{limit:1});return solutions.length?new Set(solutions[0]):null;}
function stepKeepsSolution(puzzle,bulbs,noBulbs,step){const nextBulbs=new Set(bulbs),nextNoBulbs=new Set(noBulbs);if(step.value===1){nextNoBulbs.delete(step.index);nextBulbs.add(step.index);}else{nextBulbs.delete(step.index);nextNoBulbs.add(step.index);}return solveLatarnie(puzzle,{limit:1,initialBulbs:[...nextBulbs],initialNoBulbs:[...nextNoBulbs]}).length>0;}
function correctionStep(puzzle,bulbs,noBulbs){const solution=baseSolution(puzzle);if(!solution)return null;for(const index of bulbs)if(!solution.has(index))return{kind:'wrong-bulb',index,value:0,reason:'Ta latarnia nie pasuje do rozwiązania. Usuń ją i sprawdź ponownie ten obszar.',area:[index]};for(const index of noBulbs)if(solution.has(index))return{kind:'wrong-cross',index,value:1,reason:'To pole zostało wykluczone błędnie. Usuń X — tutaj musi stanąć latarnia.',area:[index]};return null;}
function candidateSteps(puzzle,bulbs,noBulbs){const steps=[];for(const bulb of bulbs)for(const cell of visibleFrom(bulb,puzzle))if(!bulbs.has(cell)&&!noBulbs.has(cell))steps.push({kind:'visibility',index:cell,value:0,reason:'To pole jest już oświetlane przez latarnię, więc nie może zawierać kolejnej latarni.',area:[bulb,cell]});for(const wall of puzzle.walls||[]){if(!Number.isInteger(wall.clue))continue;const cells=orthogonalNeighbors(wall.index,puzzle).filter(i=>!(puzzle.walls||[]).some(w=>w.index===i));const placed=cells.filter(i=>bulbs.has(i));const available=cells.filter(i=>!bulbs.has(i)&&!noBulbs.has(i));if(placed.length===wall.clue)for(const index of available)steps.push({kind:'clue-complete',index,value:0,reason:`Ściana z liczbą ${wall.clue} ma już wymaganą liczbę latarni.`,area:[wall.index,...cells]});if(placed.length+available.length===wall.clue)for(const index of available)steps.push({kind:'clue-forced',index,value:1,reason:`Przy ścianie z liczbą ${wall.clue} wszystkie pozostałe dostępne pola muszą zawierać latarnie.`,area:[wall.index,...cells]});}
const lit=litCells(puzzle,bulbs);for(const cell of whiteCells(puzzle)){if(lit.has(cell))continue;const possible=lightSourcesFor(cell,puzzle).filter(source=>!noBulbs.has(source));if(possible.length===1)steps.push({kind:'only-light-source',index:possible[0],value:1,reason:'To pole może zostać oświetlone tylko z jednego miejsca, więc właśnie tam musi stanąć latarnia.',area:[cell,possible[0]]});}return steps;}
export function nextHumanStep(puzzle,{bulbs=new Set(),noBulbs=new Set()}={}){const correction=correctionStep(puzzle,bulbs,noBulbs);if(correction)return correction;for(const step of candidateSteps(puzzle,bulbs,noBulbs))if(stepKeepsSolution(puzzle,bulbs,noBulbs,step))return step;const solution=baseSolution(puzzle);if(!solution)return null;for(const index of solution)if(!bulbs.has(index)&&!noBulbs.has(index))return{kind:'solver-forced',index,value:1,reason:'Po uwzględnieniu wszystkich ograniczeń to pole musi zawierać latarnię.',area:[index]};for(const index of whiteCells(puzzle))if(!solution.has(index)&&!bulbs.has(index)&&!noBulbs.has(index))return{kind:'solver-excluded',index,value:0,reason:'Po uwzględnieniu wszystkich ograniczeń na tym polu nie może stać latarnia.',area:[index]};return null;}
export function humanSolve(puzzle){const bulbs=new Set(),noBulbs=new Set(),steps=[];const scoring={visibility:1,'clue-complete':1,'clue-forced':2,'only-light-source':4,'solver-forced':6,'solver-excluded':6};for(let i=0;i<puzzle.rows*puzzle.cols*8;i++){const step=nextHumanStep(puzzle,{bulbs,noBulbs});if(!step||step.kind==='wrong-bulb'||step.kind==='wrong-cross')break;steps.push(step);if(step.value===1)bulbs.add(step.index);else noBulbs.add(step.index);}return{bulbs,noBulbs,steps,score:steps.reduce((s,x)=>s+(scoring[x.kind]||1),0)};}
