import{orthogonalNeighbors,whiteCells,wallMap}from'./model.js';
import{lightSourcesFor,visibleFrom}from'./rules.js';
function buildContext(puzzle){const cells=whiteCells(puzzle),cellSet=new Set(cells),walls=wallMap(puzzle);const sources=new Map(),conflicts=new Map(),clues=[];for(const cell of cells){sources.set(cell,lightSourcesFor(cell,puzzle).filter(source=>cellSet.has(source)));conflicts.set(cell,visibleFrom(cell,puzzle).filter(other=>cellSet.has(other)));}for(const wall of puzzle.walls||[]){if(!Number.isInteger(wall.clue))continue;clues.push({index:wall.index,clue:wall.clue,cells:orthogonalNeighbors(wall.index,puzzle).filter(index=>!walls.has(index))});}return{cells,sources,conflicts,clues};}
function propagate(context,values){let changed=true;while(changed){changed=false;for(const cell of context.cells){if(values.get(cell)!==1)continue;for(const other of context.conflicts.get(cell)){const current=values.get(other);if(current===1)return false;if(current===undefined){values.set(other,0);changed=true;}}}
for(const clue of context.clues){let bulbs=0;const unknown=[];for(const cell of clue.cells){const value=values.get(cell);if(value===1)bulbs++;else if(value===undefined)unknown.push(cell);}if(bulbs>clue.clue||bulbs+unknown.length<clue.clue)return false;if(bulbs===clue.clue){for(const cell of unknown){values.set(cell,0);changed=true;}}else if(bulbs+unknown.length===clue.clue){for(const cell of unknown){values.set(cell,1);changed=true;}}}
for(const cell of context.cells){const options=context.sources.get(cell);if(options.some(source=>values.get(source)===1))continue;const unknown=options.filter(source=>values.get(source)===undefined);if(!unknown.length)return false;if(unknown.length===1){values.set(unknown[0],1);changed=true;}}
}return true;}
function chooseVariable(context,values){let best=null,bestScore=-1;for(const cell of context.cells){if(values.has(cell))continue;const score=context.conflicts.get(cell).length+context.sources.get(cell).length;if(score>bestScore){best=cell;bestScore=score;}}return best;}
export function solveLatarnie(puzzle,{limit=1,initialBulbs=[],initialNoBulbs=[]}={}){const context=buildContext(puzzle),start=new Map(),solutions=[];for(const cell of initialBulbs){if(start.get(cell)===0)return[];start.set(cell,1);}for(const cell of initialNoBulbs){if(start.get(cell)===1)return[];start.set(cell,0);}function search(values){if(solutions.length>=limit)return;const next=new Map(values);if(!propagate(context,next))return;const variable=chooseVariable(context,next);if(variable===null){solutions.push(context.cells.filter(cell=>next.get(cell)===1));return;}for(const value of[1,0]){const branch=new Map(next);branch.set(variable,value);search(branch);if(solutions.length>=limit)return;}}search(start);return solutions;}
export function hasUniqueSolution(puzzle){return solveLatarnie(puzzle,{limit:2}).length===1;}
