import{currentDateKey}from'../daily.js';
import{completeGame}from'../services/progress-service.js';
import{loadFigloState}from'../storage.js';
import{requestedGameMode,setGameMode}from'../ui/game-mode.js';
import{showGameLoader,hideGameLoader}from'../ui/game-loader.js';
import{loadLatarnieDaily}from'./daily-loader.js';
import{generateLatarnieAsync}from'./generator-async.js';
import{litCells,conflictingBulbs,clueStatus,isSolved}from'./rules.js';
import{nextHumanStep}from'./human-solver.js';
import{createLatarnieSession,loadLatarnieSession,saveLatarnieSession,clearLatarnieSession}from'./session.js';
const $=s=>document.querySelector(s);const today=currentDateKey();const requestedMode=requestedGameMode();let record=null,puzzle=null,session=null,gameMode='daily',trainingNumber=0,timerTick=null,hintTimer=null,boardResizeObserver=null;
function randomSeed(){return globalThis.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;}
function formatMs(ms){const s=Math.floor(Math.max(0,ms)/1000);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function elapsedNow(){return!session?0:session.elapsedMs+(session.runningSince?Date.now()-session.runningSince:0);}
function renderTimer(){$('#timer').textContent=formatMs(elapsedNow());}
function save(){if(gameMode==='daily'&&session)saveLatarnieSession(session);}
function startTimer(){if(!session||session.finished||session.runningSince)return;session.runningSince=Date.now();session.startedAt||=new Date().toISOString();timerTick||=setInterval(renderTimer,250);}
function pauseTimer(){if(!session?.runningSince)return;session.elapsedMs+=Date.now()-session.runningSince;session.runningSince=null;if(timerTick){clearInterval(timerTick);timerTick=null;}save();renderTimer();}
function bulbSet(){return new Set(session?.bulbs||[]);}function crossSet(){return new Set(session?.crosses||[]);}
function pushHistory(){session.history.push({bulbs:[...session.bulbs],crosses:[...session.crosses]});if(session.history.length>100)session.history.shift();}
function clearHint(){if(hintTimer)clearTimeout(hintTimer);hintTimer=null;$('#hintCard').hidden=true;for(const cell of $('#board').children)cell.classList.remove('hint','hint-target');}
function cycleCell(index){if(session.finished)return;startTimer();clearHint();pushHistory();const bulbs=bulbSet(),crosses=crossSet();if(!bulbs.has(index)&&!crosses.has(index))bulbs.add(index);else if(bulbs.has(index)){bulbs.delete(index);crosses.add(index);}else crosses.delete(index);session.bulbs=[...bulbs];session.crosses=[...crosses];save();render();if(isSolved(puzzle,bulbs))finish();}
function syncBoardCellSize(){const board=$('#board'),wrap=board?.parentElement;if(!board||!wrap||!puzzle)return;const styles=getComputedStyle(board),gap=parseFloat(styles.getPropertyValue('--gap'))||0,pad=parseFloat(styles.getPropertyValue('--pad'))||0,borderX=(parseFloat(styles.borderLeftWidth)||0)+(parseFloat(styles.borderRightWidth)||0),borderY=(parseFloat(styles.borderTopWidth)||0)+(parseFloat(styles.borderBottomWidth)||0),availableWidth=Math.floor(Math.min(wrap.clientWidth,window.innerWidth-32)),horizontalChrome=pad*2+borderX+gap*(puzzle.cols-1),verticalChrome=pad*2+borderY+gap*(puzzle.rows-1),cellSize=Math.max(24,Math.floor((availableWidth-horizontalChrome)/puzzle.cols)),boardWidth=cellSize*puzzle.cols+horizontalChrome,boardHeight=cellSize*puzzle.rows+verticalChrome;board.style.setProperty('--cell-size',`${cellSize}px`);board.style.gridTemplateColumns=`repeat(${puzzle.cols}, ${cellSize}px)`;board.style.gridTemplateRows=`repeat(${puzzle.rows}, ${cellSize}px)`;board.style.width=`${boardWidth}px`;board.style.height=`${boardHeight}px`;}
function buildBoard(){const board=$('#board');board.innerHTML='';const walls=new Map((puzzle.walls||[]).map(w=>[w.index,w]));for(let index=0;index<puzzle.rows*puzzle.cols;index++){const wall=walls.get(index);if(wall){const el=document.createElement('div');el.className='latarnia-wall';el.dataset.index=String(index);el.setAttribute('role','gridcell');if(Number.isInteger(wall.clue)){el.textContent=String(wall.clue);el.setAttribute('aria-label',`Ściana z liczbą ${wall.clue}`);}else el.setAttribute('aria-label','Ściana');board.appendChild(el);continue;}const cell=document.createElement('button');cell.type='button';cell.className='latarnia-cell';cell.dataset.index=String(index);cell.setAttribute('role','gridcell');cell.setAttribute('aria-label','Puste pole');cell.addEventListener('click',()=>cycleCell(index));board.appendChild(cell);}board.style.setProperty('--cols',puzzle.cols);board.style.setProperty('--rows',puzzle.rows);requestAnimationFrame(syncBoardCellSize);if(!boardResizeObserver&&'ResizeObserver'in globalThis){boardResizeObserver=new ResizeObserver(syncBoardCellSize);boardResizeObserver.observe(board.parentElement);}}
function render(){if(!puzzle||!session)return;const bulbs=bulbSet(),crosses=crossSet(),lit=litCells(puzzle,bulbs),conflicts=conflictingBulbs(puzzle,bulbs),walls=new Map((puzzle.walls||[]).map(w=>[w.index,w]));for(const child of $('#board').children){const index=Number(child.dataset.index);const wall=walls.get(index);if(wall){if(Number.isInteger(wall.clue)){const status=clueStatus(puzzle,bulbs,wall);child.classList.toggle('satisfied',status.satisfied);child.classList.toggle('over',status.over);}continue;}child.classList.toggle('is-lit',lit.has(index));child.classList.toggle('has-bulb',bulbs.has(index));child.classList.toggle('has-cross',crosses.has(index));child.classList.toggle('conflict',conflicts.has(index));child.innerHTML=bulbs.has(index)?'<span class="bulb" aria-hidden="true">✦</span>':crosses.has(index)?'<span class="cross" aria-hidden="true">×</span>':'';child.setAttribute('aria-label',bulbs.has(index)?'Latarnia':crosses.has(index)?'Wykluczone pole':lit.has(index)?'Oświetlone pole':'Nieoświetlone pole');}
$('#bulbCounter').textContent=String(bulbs.size);$('#undo').disabled=!session.history.length||session.finished;$('#mobileUndo').disabled=!session.history.length||session.finished;$('#hint').disabled=session.finished;$('#mobileHint').disabled=session.finished;renderTimer();}
function undo(){if(!session.history.length||session.finished)return;clearHint();const previous=session.history.pop();session.bulbs=previous.bulbs;session.crosses=previous.crosses;save();render();}
function reset(){if(session.finished)return;clearHint();pauseTimer();session.bulbs=[];session.crosses=[];session.history=[];session.elapsedMs=0;session.runningSince=null;session.startedAt=null;save();render();}
function showHint(){if(session.finished)return;const step=nextHumanStep(puzzle,{bulbs:bulbSet(),noBulbs:crossSet()});const card=$('#hintCard');card.hidden=false;$('#hintText').textContent=step?.reason||'Nie widzę teraz pewnego kolejnego kroku. Sprawdź ściany z liczbami i nieoświetlone pola.';if(step){session.hintsUsed=(session.hintsUsed||0)+1;save();const targets=new Set(step.indices||[step.index]);for(const cell of $('#board').children){const index=Number(cell.dataset.index);cell.classList.toggle('hint',step.area?.includes(index));cell.classList.toggle('hint-target',targets.has(index));}hintTimer=setTimeout(()=>{for(const cell of $('#board').children)cell.classList.remove('hint','hint-target');},3500);}if(matchMedia('(max-width: 767px)').matches)requestAnimationFrame(()=>card.scrollIntoView({behavior:'smooth',block:'center'}));}
function finish(){pauseTimer();session.finished=true;const ms=session.elapsedMs;let best=loadFigloState(today).games.latarnie?.bestTimeMs||null;if(gameMode==='daily'){save();const result=completeGame({gameId:'latarnie',puzzleId:record.puzzleId,date:today,elapsedMs:ms,mode:'daily',startedAt:session.startedAt});best=result.state.games.latarnie?.bestTimeMs||ms;}$('#finalTime').textContent=formatMs(ms);$('#bestTime').textContent=best?formatMs(best):'—';$('#done').hidden=false;render();}
async function loadDaily(){showGameLoader('Przygotowuję dzisiejsze Latarnie…');$('#board').setAttribute('aria-busy','true');try{record=await loadLatarnieDaily(today);puzzle=record.puzzle;gameMode='daily';setGameMode('daily');$('#roundLabel').textContent='Dzisiaj';$('#done').hidden=true;let restored=loadLatarnieSession({date:today,seed:record.puzzleId});if(restored?.finished){clearLatarnieSession(today);restored=null;}session=restored||createLatarnieSession({date:today,seed:record.puzzleId});buildBoard();render();if(session.runningSince)timerTick=setInterval(renderTimer,250);}finally{$('#board').removeAttribute('aria-busy');hideGameLoader();}}
async function loadTraining(){showGameLoader('Przygotowuję planszę treningową…');$('#board').setAttribute('aria-busy','true');try{const seed=randomSeed();const generated=await generateLatarnieAsync({seed,difficulty:'medium'});record={puzzleId:`latarnie-training:${seed}`,puzzle:generated.puzzle,solution:generated.solution};puzzle=generated.puzzle;session=createLatarnieSession({date:today,seed:record.puzzleId});gameMode='training';setGameMode('training');trainingNumber+=1;$('#roundLabel').textContent=`Trening #${trainingNumber}`;$('#done').hidden=true;clearHint();buildBoard();render();}finally{$('#board').removeAttribute('aria-busy');hideGameLoader();}}
async function start(){const state=loadFigloState(today);if(requestedMode==='training'||state.daily.completedGames.includes('latarnie'))return loadTraining();return loadDaily();}
$('#undo').addEventListener('click',undo);$('#mobileUndo').addEventListener('click',undo);$('#reset').addEventListener('click',reset);$('#mobileReset').addEventListener('click',reset);$('#hint').addEventListener('click',showHint);$('#mobileHint').addEventListener('click',showHint);$('#hintClose').addEventListener('click',clearHint);$('#rulesTop').addEventListener('click',()=>{$('#rules').open=true;$('#rules').scrollIntoView({behavior:'smooth'});});$('#replay').addEventListener('click',()=>loadTraining().catch(console.error));window.addEventListener('resize',syncBoardCellSize);window.addEventListener('pagehide',pauseTimer);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseTimer();});start().catch(error=>{console.error('Latarnie start failure',error);hideGameLoader();$('#loadError').hidden=false;});
