import {SHAPES,rectArea,rectShape} from './model.js';
import {hasUniqueSolution} from './solver.js';
function hashSeed(value){let h=2166136261;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function mulberry32(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
const randInt=(rng,min,max)=>min+Math.floor(rng()*(max-min+1));
const choose=(rng,a)=>a[Math.floor(rng()*a.length)];
function shuffle(rng,values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function splits(rect){const out=[];for(let cut=1;cut<rect.width;cut++){const a={row:rect.row,col:rect.col,width:cut,height:rect.height},b={row:rect.row,col:rect.col+cut,width:rect.width-cut,height:rect.height};if(rectArea(a)>=2&&rectArea(b)>=2)out.push({a,b});}for(let cut=1;cut<rect.height;cut++){const a={row:rect.row,col:rect.col,width:rect.width,height:cut},b={row:rect.row+cut,col:rect.col,width:rect.width,height:rect.height-cut};if(rectArea(a)>=2&&rectArea(b)>=2)out.push({a,b});}return out;}
function partition(rows,cols,count,rng){const regions=[{row:0,col:0,width:cols,height:rows}];while(regions.length<count){const choices=regions.map((rect,index)=>({rect,index,s:splits(rect)})).filter(x=>x.s.length);if(!choices.length)return null;choices.sort((a,b)=>rectArea(b.rect)-rectArea(a.rect));const target=choose(rng,choices.slice(0,Math.min(4,choices.length)));const split=choose(rng,target.s);regions.splice(target.index,1,split.a,split.b);}return regions;}
function anchor(region,rng){return{row:randInt(rng,region.row,region.row+region.height-1),col:randInt(rng,region.col,region.col+region.width-1)};}
function clueFor(region,index,rng){const a=anchor(region,rng);return{id:`b${index+1}`,row:a.row,col:a.col,area:rectArea(region),shape:rectShape(region)};}
function relaxationBudget(difficulty){return difficulty==='easy'?1:difficulty==='hard'?5:3;}
function relax(puzzle,rng,difficulty){let current=structuredClone(puzzle),relaxed=0;for(const clueId of shuffle(rng,current.clues.map(c=>c.id))){if(relaxed>=relaxationBudget(difficulty))break;const i=current.clues.findIndex(c=>c.id===clueId);const trial=structuredClone(current);trial.clues[i]={...trial.clues[i],shape:SHAPES.ANY};if(hasUniqueSolution(trial)){current=trial;relaxed++;}}return current;}
export function generateBloki({seed,rows=6,cols=6,difficulty='medium',maxAttempts=400}={}){if(seed==null)throw new Error('Bloki generator requires a seed');const base=hashSeed(seed);for(let attempt=0;attempt<maxAttempts;attempt++){const rng=mulberry32((base+Math.imul(attempt+1,0x9E3779B1))>>>0);const count=difficulty==='easy'?randInt(rng,6,7):difficulty==='hard'?randInt(rng,9,10):randInt(rng,7,9);const regions=partition(rows,cols,count,rng);if(!regions)continue;const puzzle={version:1,game:'bloki',seed:String(seed),rows,cols,difficulty,clues:regions.map((r,i)=>clueFor(r,i,rng))};if(!hasUniqueSolution(puzzle))continue;const result=relax(puzzle,rng,difficulty);if(hasUniqueSolution(result))return result;}throw new Error(`Could not generate unique Bloki puzzle for seed ${seed}`);}
