import {cellKey,rectCells} from './model.js';
import {validatePlacement} from './rules.js';
function factors(area,maxW,maxH){const out=[];for(let h=1;h<=maxH;h++){if(area%h)continue;const w=area/h;if(w<=maxW)out.push([w,h]);}return out;}
function candidateSizes(puzzle,clue){if(clue.area!=null)return factors(clue.area,puzzle.cols,puzzle.rows);const out=[];for(let h=1;h<=puzzle.rows;h++)for(let w=1;w<=puzzle.cols;w++)out.push([w,h]);return out;}
export function candidatesForClue(puzzle,clue){const out=[];for(const [width,height] of candidateSizes(puzzle,clue)){const minRow=Math.max(0,clue.row-height+1),maxRow=Math.min(clue.row,puzzle.rows-height);const minCol=Math.max(0,clue.col-width+1),maxCol=Math.min(clue.col,puzzle.cols-width);for(let row=minRow;row<=maxRow;row++)for(let col=minCol;col<=maxCol;col++){const rect={row,col,width,height};if(validatePlacement(puzzle,rect,clue.id))out.push(rect);}}return out;}
export function solve(puzzle,{limit=1}={}){const map=new Map(puzzle.clues.map(clue=>[clue.id,candidatesForClue(puzzle,clue)]));const solutions=[];search(puzzle,map,puzzle.clues.map(c=>c.id),new Set(),[],solutions,limit);return solutions;}
function search(puzzle,map,remaining,used,placements,solutions,limit){if(solutions.length>=limit)return;if(!remaining.length){if(used.size===puzzle.rows*puzzle.cols)solutions.push(placements.map(p=>({clueId:p.clueId,rect:{...p.rect}})));return;}let bestId=null,best=null;for(const id of remaining){const avail=map.get(id).filter(rect=>rectCells(rect).every(cell=>!used.has(cellKey(cell.row,cell.col))));if(!avail.length)return;if(best===null||avail.length<best.length){bestId=id;best=avail;if(avail.length===1)break;}}const next=remaining.filter(id=>id!==bestId);for(const rect of best){const keys=rectCells(rect).map(c=>cellKey(c.row,c.col));keys.forEach(k=>used.add(k));placements.push({clueId:bestId,rect});search(puzzle,map,next,used,placements,solutions,limit);placements.pop();keys.forEach(k=>used.delete(k));if(solutions.length>=limit)return;}}
export function countSolutions(puzzle,limit=2){return solve(puzzle,{limit}).length;}
export function hasUniqueSolution(puzzle){return countSolutions(puzzle,2)===1;}
