import {currentDateKey} from '../daily.js';
import {getDailyGame} from '../services/daily-service.js';
import {completeGame} from '../services/progress-service.js';
import {getIdentity} from '../services/identity-service.js';
import {track} from '../services/analytics-service.js';
import {rectArea,rectContains,SHAPES} from './model.js';
import {validatePlacement,isSolved} from './rules.js';
import {solve} from './solver.js';
import {cellsOverlap,rectForDrag,applyPlacementReplacingOverlaps} from './interaction.js';
import {restoreOrCreateBlokiSession,saveBlokiSession,clearBlokiSession} from './session.js';

const $=s=>document.querySelector(s);const boardEl=$('#board');const today=currentDateKey();const identity=getIdentity();
const CLUE_COLORS=[
  {line:'#67C7FF',bg:'rgba(103,199,255,.20)'},
  {line:'#FF9C5B',bg:'rgba(255,156,91,.20)'},
  {line:'#A98FFF',bg:'rgba(169,143,255,.20)'},
  {line:'#F5C84C',bg:'rgba(245,200,76,.20)'},
  {line:'#5FD0A2',bg:'rgba(95,208,162,.20)'},
  {line:'#FF7F9F',bg:'rgba(255,127,159,.20)'},
  {line:'#62D5D0',bg:'rgba(98,213,208,.20)'},
  {line:'#A9B7C2',bg:'rgba(169,183,194,.20)'},
  {line:'#B7DD62',bg:'rgba(183,221,98,.20)'},
  {line:'#D99CFF',bg:'rgba(217,156,255,.20)'}
];
let record=null,puzzle=null,solution=null,session=null,timerTick=null,drag=null,feedbackTimer=null,hintTarget=null,hintTimer=null;
function formatMs(ms){const sec=Math.floor(Math.max(0,ms)/1000);return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function elapsedNow(){return!session?0:session.elapsedMs+(session.runningSince?Date.now()-session.runningSince:0);}
function ensureTimerStarted(){if(!session.runningSince&&!session.finished){session.runningSince=Date.now();session.startedAt||=new Date().toISOString();track('game_started',{gameId:'bloki',puzzleId:record?.puzzleId,date:today,localId:identity.localId});}timerTick||=setInterval(renderTimer,250);}
function pauseTimer(){if(!session?.runningSince)return;session.elapsedMs+=Date.now()-session.runningSince;session.runningSince=null;save();}
function renderTimer(){$('#timer').textContent=formatMs(elapsedNow());}
function save(){if(session)saveBlokiSession(session);}
function rectEqual(a,b){return a.row===b.row&&a.col===b.col&&a.width===b.width&&a.height===b.height;}
function clueShapeClass(shape){if(shape===SHAPES.SQUARE)return'square';if(shape===SHAPES.WIDE)return'wide';if(shape===SHAPES.TALL)return'tall';return'any';}
function clueName(shape){if(shape===SHAPES.SQUARE)return'kwadrat';if(shape===SHAPES.WIDE)return'szeroki prostokąt';if(shape===SHAPES.TALL)return'wysoki prostokąt';return'dowolny prostokąt';}
function clueColor(clueId){const numeric=Math.max(0,(Number(String(clueId).replace(/\D/g,''))||1)-1);return CLUE_COLORS[numeric%CLUE_COLORS.length];}
function clueVars(clueId,prefix='clue'){const color=clueColor(clueId);return`--${prefix}:${color.line};--${prefix}-bg:${color.bg}`;}
function placementStyle(rect,clueId){return`--r:${rect.row};--c:${rect.col};--w:${rect.width};--h:${rect.height};${clueVars(clueId,'block')}`;}
function clueMarkup(clue){const className=clueShapeClass(clue.shape);const inner=clue.area!=null?`<span class="clue-area">${clue.area}</span>`:'<span class="clue-dot" aria-hidden="true"></span>';return`<span class="clue-token ${className}" style="${clueVars(clue.id)}">${inner}</span>`;}
function clueLabel(clue){const bits=[];if(clue.area!=null)bits.push(`${clue.area} pól`);bits.push(clueName(clue.shape));return`Wskazówka: ${bits.join(', ')}`;}
function clearHint({render=false}={}){if(hintTimer)clearTimeout(hintTimer);hintTimer=null;hintTarget=null;if(render&&puzzle&&session)renderBoard();}
function renderBoard(){boardEl.innerHTML='';for(let row=0;row<puzzle.rows;row++)for(let col=0;col<puzzle.cols;col++){const cell=document.createElement('button');cell.type='button';cell.className='bloki-cell';cell.dataset.row=String(row);cell.dataset.col=String(col);cell.setAttribute('role','gridcell');const clue=puzzle.clues.find(c=>c.row===row&&c.col===col);if(clue){cell.classList.add('clue-cell');cell.innerHTML=clueMarkup(clue);cell.setAttribute('aria-label',clueLabel(clue));}else cell.setAttribute('aria-label',`Wiersz ${row+1}, kolumna ${col+1}`);boardEl.appendChild(cell);}for(const p of session.placements){const overlay=document.createElement('div');overlay.className='block-placement';overlay.style.cssText=placementStyle(p.rect,p.clueId);overlay.dataset.clueId=p.clueId;boardEl.appendChild(overlay);}if(hintTarget){const hint=document.createElement('div');hint.className='block-placement hint-highlight';hint.style.cssText=placementStyle(hintTarget.rect,hintTarget.clueId);hint.setAttribute('aria-hidden','true');boardEl.appendChild(hint);}if(drag){const previewRect=rectForDrag(drag);const preview=document.createElement('div');preview.className='block-placement preview';preview.style.cssText=placementStyle(previewRect,'preview');preview.innerHTML=`<span class="preview-count" aria-hidden="true">${rectArea(previewRect)}</span>`;boardEl.appendChild(preview);}const filled=session.placements.reduce((sum,p)=>sum+rectArea(p.rect),0);$('#filledCounter').textContent=`${filled}/${puzzle.rows*puzzle.cols}`;renderTimer();updateButtons();}
function setFeedback(copy,type=''){const el=$('#feedback');el.textContent=copy;el.className=`feedback${type?` ${type}`:''}`;if(feedbackTimer)clearTimeout(feedbackTimer);if(type==='error')feedbackTimer=setTimeout(()=>{if(!session.finished){el.textContent='Przeciągnij po planszy, żeby zaznaczyć blok.';el.className='feedback';}},1800);}
function pushHistory(){session.history.push(session.placements.map(p=>({clueId:p.clueId,rect:{...p.rect}})));if(session.history.length>100)session.history.shift();}
function tryPlace(rect){if(session.finished)return;ensureTimerStarted();const clues=puzzle.clues.filter(c=>rectContains(rect,c));if(clues.length!==1){setFeedback(clues.length?'Ten obszar może zawierać tylko jedną wskazówkę.':'Każdy blok musi zawierać wskazówkę.','error');return;}const clue=clues[0];if(!validatePlacement(puzzle,rect,clue.id)){const reason=clue.area!=null&&rectArea(rect)!==clue.area?`Ten blok musi mieć dokładnie ${clue.area} pól.`:`Ten blok musi mieć kształt: ${clueName(clue.shape)}.`;setFeedback(reason,'error');return;}const existing=session.placements.find(p=>p.clueId===clue.id);if(existing&&rectEqual(existing.rect,rect))return;const replacedOther=session.placements.some(p=>p.clueId!==clue.id&&cellsOverlap(p.rect,rect));pushHistory();session.placements=applyPlacementReplacingOverlaps(session.placements,{clueId:clue.id,rect});if(hintTarget&&hintTarget.clueId===clue.id&&rectEqual(hintTarget.rect,rect))clearHint();save();renderBoard();if(isSolved(puzzle,session.placements))finish();else setFeedback(replacedOther?'Poprawiono blok — kolidujące zaznaczenie zostało zastąpione.':'Dobrze. Zaznacz kolejny blok.');}
function cellFromPoint(x,y){const el=document.elementFromPoint(x,y)?.closest?.('.bloki-cell');if(!el||!boardEl.contains(el))return null;return{row:Number(el.dataset.row),col:Number(el.dataset.col)};}
function onPointerDown(event){if(session.finished)return;const cell=event.target.closest('.bloki-cell');if(!cell)return;event.preventDefault();const start={row:Number(cell.dataset.row),col:Number(cell.dataset.col)};const existing=session.placements.find(p=>rectContains(p.rect,start));drag={pointerId:event.pointerId,start,end:start,baseRect:existing?{...existing.rect}:null,baseClueId:existing?.clueId||null};boardEl.setPointerCapture?.(event.pointerId);renderBoard();}
function onPointerMove(event){if(!drag||drag.pointerId!==event.pointerId)return;const cell=cellFromPoint(event.clientX,event.clientY);if(!cell||cell.row===drag.end.row&&cell.col===drag.end.col)return;drag.end=cell;renderBoard();}
function onPointerUp(event){if(!drag||drag.pointerId!==event.pointerId)return;const current=drag;drag=null;boardEl.releasePointerCapture?.(event.pointerId);const moved=current.start.row!==current.end.row||current.start.col!==current.end.col;if(!moved&&current.baseClueId){const existing=session.placements.find(p=>p.clueId===current.baseClueId);if(existing){ensureTimerStarted();pushHistory();session.placements=session.placements.filter(p=>p.clueId!==current.baseClueId);save();renderBoard();setFeedback('Blok usunięty.');return;}}const rect=rectForDrag(current);renderBoard();tryPlace(rect);}
function updateButtons(){const disabled=!session.history.length||session.finished;$('#undo').disabled=disabled;$('#mobileUndo').disabled=disabled;$('#hint').disabled=session.finished;$('#mobileHint').disabled=session.finished;}
function undo(){if(!session.history.length||session.finished)return;clearHint();session.placements=session.history.pop();save();renderBoard();setFeedback('Cofnięto ostatni ruch.');}
function reset(){if(session.finished)return;clearHint();clearBlokiSession(today);session=restoreOrCreateBlokiSession({date:today,seed:record.puzzleId});renderBoard();setFeedback('Plansza wyczyszczona.');}
function showHint(){if(session.finished)return;ensureTimerStarted();const target=solution.find(s=>!session.placements.some(p=>p.clueId===s.clueId&&rectEqual(p.rect,s.rect)));if(!target){setFeedback('Wszystkie bloki są już na właściwych miejscach.');return;}clearHint();hintTarget={clueId:target.clueId,rect:{...target.rect}};session.hintsUsed=(session.hintsUsed||0)+1;save();track('hint_used',{gameId:'bloki',puzzleId:record?.puzzleId,date:today,localId:identity.localId});renderBoard();setFeedback('Podświetlono jeden poprawny obszar. Zaznacz go samodzielnie.');hintTimer=setTimeout(()=>{hintTarget=null;hintTimer=null;if(!session.finished)renderBoard();},3500);}
function finish(){clearHint();session.finished=true;pauseTimer();const ms=session.elapsedMs;save();const result=completeGame({gameId:'bloki',puzzleId:record.puzzleId,date:today,elapsedMs:ms,mode:'daily',startedAt:session.startedAt||null});track('game_completed',{...result.event,localId:identity.localId,hintsUsed:session.hintsUsed||0});if(result.firstDayCompletionToday)track('daily_completed',{date:today,localId:identity.localId});$('#finalTime').textContent=formatMs(ms);$('#bestTime').textContent=formatMs(result.state.games.bloki?.bestTimeMs||ms);$('#doneCopy').textContent=result.firstDayCompletionToday?'Dzisiejsze Figlo zrobione!':'Bloki zaliczone. Zostały kolejne gry z zestawu.';$('#done').hidden=false;$('#backToSet').focus();renderBoard();setFeedback('Bloki ukończone!','success');}
function replay(){clearHint();clearBlokiSession(today);session=restoreOrCreateBlokiSession({date:today,seed:record.puzzleId});$('#done').hidden=true;track('game_replayed',{gameId:'bloki',puzzleId:record.puzzleId,date:today,localId:identity.localId});renderBoard();setFeedback('Nowa próba. Powodzenia!');}
async function start(){try{record=await getDailyGame('bloki',today);puzzle=record.puzzle;solution=solve(puzzle,{limit:1})[0];if(!solution)throw new Error('Bloki puzzle has no solution');session=restoreOrCreateBlokiSession({date:today,seed:record.puzzleId});if(session.runningSince)timerTick=setInterval(renderTimer,250);track('game_opened',{gameId:'bloki',puzzleId:record.puzzleId,date:today,localId:identity.localId});renderBoard();setFeedback(session.finished?'Bloki ukończone!':'Przeciągnij po planszy, żeby zaznaczyć blok.',session.finished?'success':'');}catch(error){console.error('bloki daily load failure',error);$('#loadError').hidden=false;boardEl.setAttribute('aria-disabled','true');}}
boardEl.addEventListener('pointerdown',onPointerDown);boardEl.addEventListener('pointermove',onPointerMove);boardEl.addEventListener('pointerup',onPointerUp);boardEl.addEventListener('pointercancel',()=>{drag=null;renderBoard();});
$('#undo').addEventListener('click',undo);$('#mobileUndo').addEventListener('click',undo);$('#hint').addEventListener('click',showHint);$('#mobileHint').addEventListener('click',showHint);$('#reset').addEventListener('click',reset);$('#mobileReset').addEventListener('click',reset);$('#rulesTop').addEventListener('click',()=>{$('#rules').open=true;$('#rules').scrollIntoView({behavior:'smooth'});});$('#replay').addEventListener('click',replay);
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearHint();pauseTimer();}else if(session&&!session.finished&&session.history.length){session.runningSince=Date.now();save();timerTick||=setInterval(renderTimer,250);}});window.addEventListener('pagehide',pauseTimer);start();
