import { N, allCells, rc, regionAt, setRegions } from './puzzle.js';
import { clearManualXs, conflicts, createGameState, cycleCell, isSolved, snapshot, visibleXs } from './game.js';
import { getHint } from './hints.js';
import { generatePuzzle } from './generator.js';
const $=s=>document.querySelector(s),board=$('#board'),timer=$('#timer'),undoBtn=$('#undo'),hintBtn=$('#hint'),hintCard=$('#hintCard'),hintText=$('#hintText'),autoXInput=$('#autoX'),done=$('#done'),finalTime=$('#finalTime'),nextPuzzleBtn=$('#nextPuzzle'),roundLabel=$('#roundLabel');
let state=createGameState(),history=[],started=false,start=0,tick=null,finished=false,practiceNumber=1,autoXEnabled=localStorage.getItem('figlo-auto-x')==='1';autoXInput.checked=autoXEnabled;
const crownMarkup='<span class="mark crown" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M4 24h24l-2 5H6l-2-5Zm1-15 7 6 4-10 4 10 7-6-2 12H7L5 9Z"/></svg></span>';
const fmt=ms=>{const s=Math.floor(ms/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
function localDateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateFromKey(k){if(!k)return null;const[y,m,d]=k.split('-').map(Number);return y&&m&&d?new Date(y,m-1,d):null}function dayDistance(a,b){const x=dateFromKey(a),y=dateFromKey(b);return x&&y?Math.round((y-x)/86400000):null}
function bumpStreak(streakKey,lastKey,today){const last=localStorage.getItem(lastKey);let streak=Number(localStorage.getItem(streakKey))||0;if(last!==today){streak=dayDistance(last,today)===1?Math.max(1,streak+1):1;localStorage.setItem(streakKey,String(streak));localStorage.setItem(lastKey,today)}return streak}
function refreshGameStats(){const best=Number(localStorage.getItem('figlo-crowns-best-ms'))||0;$('#crownsBest').textContent=best?fmt(best):'—';$('#crownsCount').textContent=localStorage.getItem('figlo-crowns-completed-count')||'0';const streak=Number(localStorage.getItem('figlo-crowns-streak'))||0;$('#crownsStreak').textContent=streak?`🔥 ${streak}`:'—'}
function saveCompletion(ms){const today=localDateKey(),best=Number(localStorage.getItem('figlo-crowns-best-ms'))||0;if(!best||ms<best)localStorage.setItem('figlo-crowns-best-ms',String(ms));const count=(Number(localStorage.getItem('figlo-crowns-completed-count'))||0)+1;localStorage.setItem('figlo-crowns-completed-count',String(count));bumpStreak('figlo-crowns-streak','figlo-crowns-last-date',today);const oldFigloStreak=Number(localStorage.getItem('figlo-streak'))||0;if(!localStorage.getItem('figlo-crowns-streak')&&oldFigloStreak)localStorage.setItem('figlo-crowns-streak',String(oldFigloStreak));const previousGlobalDate=localStorage.getItem('figlo-last-play-date');if(previousGlobalDate!==today){bumpStreak('figlo-streak','figlo-last-play-date',today);const days=(Number(localStorage.getItem('figlo-active-days'))||0)+1;localStorage.setItem('figlo-active-days',String(days))}localStorage.setItem('figlo-total-completed',String((Number(localStorage.getItem('figlo-total-completed'))||0)+1));localStorage.setItem('figlo-crowns-completed-date',today);refreshGameStats()}
function startTimer(){if(started||finished)return;started=true;start=Date.now();tick=setInterval(()=>timer.textContent=fmt(Date.now()-start),250)}function stopTimer(){if(tick)clearInterval(tick);tick=null}function clearHint(){[...board.children].forEach(c=>c.classList.remove('hint-candidate','hint-error','hint-eliminate','hint-area','hint-focus'));hintCard.classList.remove('show')}
function regionBorders(i,e){const[r,c]=rc(i),reg=regionAt(i);if(r===0||regionAt(i-N)!==reg)e.classList.add('rt');if(c===N-1||regionAt(i+1)!==reg)e.classList.add('rr');if(r===N-1||regionAt(i+N)!==reg)e.classList.add('rb');if(c===0||regionAt(i-1)!==reg)e.classList.add('rl')}
function render(){const xs=visibleXs(state,autoXEnabled),bad=conflicts(state.crowns);board.innerHTML='';board.classList.toggle('board--solved',finished);for(const i of allCells){const cell=document.createElement('button');const[r,c]=rc(i);cell.type='button';cell.className=`cell r${regionAt(i)}`;cell.setAttribute('aria-label',`Wiersz ${r+1}, kolumna ${c+1}`);regionBorders(i,cell);if(bad.has(i))cell.classList.add('bad');if(state.crowns.has(i))cell.innerHTML=crownMarkup;else if(xs.has(i))cell.innerHTML='<span class="mark x-mark" aria-hidden="true">×</span>';cell.addEventListener('click',()=>makeMove(i));board.appendChild(cell)}undoBtn.disabled=!history.length||finished;hintBtn.disabled=finished;done.classList.toggle('show',finished)}
function makeMove(i){if(finished)return;startTimer();clearHint();history.push(snapshot(state));state=cycleCell(state,i,{autoXEnabled});if(isSolved(state)){finished=true;const ms=Date.now()-start;timer.textContent=fmt(ms);stopTimer();finalTime.textContent=`Czas: ${timer.textContent}`;saveCompletion(ms)}render()}
function showHint(){if(finished)return;clearHint();const h=getHint(state,history);if(!h){hintText.textContent='Nie znalazłem teraz prostej, uczciwej dedukcji.';hintCard.classList.add('show');return}for(const i of h.area||[])board.children[i]?.classList.add('hint-area');for(const i of h.focus||[])board.children[i]?.classList.add('hint-focus');for(const i of h.cells||[])board.children[i]?.classList.add(h.kind==='error'?'hint-error':'hint-candidate');for(const i of h.eliminate||[])board.children[i]?.classList.add('hint-eliminate');hintText.innerHTML=`<div class="hint-section"><span class="hint-label">Dlaczego</span><p class="hint-copy"></p></div><div class="hint-section"><span class="hint-label">Co zrobić</span><p class="hint-copy"></p></div>`;const copies=hintText.querySelectorAll('.hint-copy');copies[0].textContent=h.reason||h.text;copies[1].textContent=h.action||h.text;hintCard.classList.add('show')}
function resetRound(){state=createGameState();history=[];finished=false;started=false;stopTimer();timer.textContent='00:00';finalTime.textContent='';clearHint();render()}function practiceSeed(){return globalThis.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
undoBtn.addEventListener('click',()=>{if(!history.length||finished)return;clearHint();const p=history.pop();state=createGameState(p.crowns,p.manualXs);render()});$('#reset').addEventListener('click',resetRound);$('#clearMarks').addEventListener('click',()=>{if(finished||state.manualXs.size===0)return;startTimer();clearHint();history.push(snapshot(state));state=clearManualXs(state);render()});hintBtn.addEventListener('click',showHint);$('#hintClose').addEventListener('click',clearHint);nextPuzzleBtn.addEventListener('click',async()=>{nextPuzzleBtn.disabled=true;nextPuzzleBtn.textContent='Generuję…';await new Promise(r=>requestAnimationFrame(r));try{const p=generatePuzzle(practiceSeed());setRegions(p.regions);practiceNumber++;roundLabel.textContent=`Trening • #${practiceNumber}`;resetRound();nextPuzzleBtn.textContent='Następna plansza'}catch(e){console.error(e);nextPuzzleBtn.textContent='Spróbuj ponownie';nextPuzzleBtn.disabled=false;return}nextPuzzleBtn.disabled=false});autoXInput.addEventListener('change',()=>{autoXEnabled=autoXInput.checked;localStorage.setItem('figlo-auto-x',autoXEnabled?'1':'0');clearHint();render()});
if(!localStorage.getItem('figlo-crowns-streak')&&localStorage.getItem('figlo-streak'))localStorage.setItem('figlo-crowns-streak',localStorage.getItem('figlo-streak'));refreshGameStats();render();
