import { N, allCells, rc, regionAt, setRegions } from './puzzle.js';
import { clearManualXs, conflicts, createGameState, cycleCell, isSolved, snapshot, visibleXs } from './game.js';
import { getHint } from './hints.js';
import { generatePuzzle } from './generator.js';

const STORAGE_KEY='figlo_user_state_v2';
const $=s=>document.querySelector(s);
const board=$('#board'),timer=$('#timer'),undoBtn=$('#undo'),hintBtn=$('#hint'),hintCard=$('#hintCard'),hintText=$('#hintText'),autoXInput=$('#autoX'),done=$('#done'),finalTime=$('#finalTime'),nextPuzzleBtn=$('#nextPuzzle'),roundLabel=$('#roundLabel'),feedback=$('#feedback'),mobileAutoX=$('#mobileAutoX');
const fmt=ms=>{const s=Math.floor(ms/1000);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const localDateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateDiff=(a,b)=>{if(!a||!b)return null;return Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000)};

function migrateLegacy(){const today=localDateKey();const completed=localStorage.getItem('figlo-crowns-completed-date')===today;return{version:2,user:{streak:Number(localStorage.getItem('figlo-streak'))||0,bestStreak:Number(localStorage.getItem('figlo-best-streak'))||Number(localStorage.getItem('figlo-streak'))||0,completedDays:Number(localStorage.getItem('figlo-active-days'))||0,completedGames:Number(localStorage.getItem('figlo-total-completed'))||Number(localStorage.getItem('figlo-crowns-completed-count'))||0,lastCompletedDate:localStorage.getItem('figlo-last-play-date')||null},daily:{date:today,requiredGames:['korony'],completedGames:completed?['korony']:[]},games:{korony:{bestTimeMs:Number(localStorage.getItem('figlo-crowns-best-ms'))||null,completedCount:Number(localStorage.getItem('figlo-crowns-completed-count'))||0,totalTimeMs:Number(localStorage.getItem('figlo-crowns-total-ms'))||0}},settings:{autoX:localStorage.getItem('figlo-auto-x')==='1'},history:{completedDates:[]}}}
function loadFiglo(){let s;try{s=JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{}if(!s||s.version!==2)s=migrateLegacy();const today=localDateKey();if(s.daily?.date!==today)s.daily={date:today,requiredGames:['korony'],completedGames:[]};s.user=s.user||{streak:0,bestStreak:0,completedDays:0,completedGames:0,lastCompletedDate:null};s.games=s.games||{};s.games.korony=s.games.korony||{bestTimeMs:null,completedCount:0,totalTimeMs:0};s.settings=s.settings||{autoX:false};s.history=s.history||{completedDates:[]};return s}
let figlo=loadFiglo();
const persist=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(figlo));
let state=createGameState(),history=[],started=false,start=0,tick=null,finished=false,practiceNumber=1,autoXEnabled=Boolean(figlo.settings.autoX);
autoXInput.checked=autoXEnabled;mobileAutoX.setAttribute('aria-pressed',String(autoXEnabled));

const crownMarkup='<span class="mark crown" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M4 24h24l-2 5H6l-2-5Zm1-15 7 6 4-10 4 10 7-6-2 12H7L5 9Z"/></svg></span>';
function startTimer(){if(started||finished)return;started=true;start=Date.now();tick=setInterval(()=>timer.textContent=fmt(Date.now()-start),250)}
function stopTimer(){if(tick)clearInterval(tick);tick=null}
function clearHint(){[...board.children].forEach(c=>c.classList.remove('hint-candidate','hint-error','hint-eliminate','hint-area','hint-focus'));hintCard.classList.remove('show')}
function regionBorders(i,e){const[r,c]=rc(i),reg=regionAt(i);if(r===0||regionAt(i-N)!==reg)e.classList.add('rt');if(c===N-1||regionAt(i+1)!==reg)e.classList.add('rr');if(r===N-1||regionAt(i+N)!==reg)e.classList.add('rb');if(c===0||regionAt(i-1)!==reg)e.classList.add('rl')}
function cellState(i,xs){if(state.crowns.has(i))return'korona';if(xs.has(i))return'X';return'puste'}
function refreshStats(){const g=figlo.games.korony;$('#crownsBest').textContent=g.bestTimeMs?fmt(g.bestTimeMs):'—';$('#modalBest').textContent=g.bestTimeMs?fmt(g.bestTimeMs):'—';$('#crownsCount').textContent=String(g.completedCount||0);$('#crownsStreak').textContent=figlo.user.streak?String(figlo.user.streak):'—'}
function updateFeedback(bad){feedback.className='feedback';if(finished){feedback.textContent='Poziom ukończony. Świetna robota.';feedback.classList.add('success');return}if(bad.size){feedback.textContent='Te korony łamią jedną z zasad.';feedback.classList.add('error');return}const left=N-state.crowns.size;feedback.textContent=left===N?'Powodzenia. Znajdź miejsce dla każdej korony.':left===1?'Została ostatnia korona.':`Dobrze idzie. Zostało koron: ${left}.`}
function render(){const xs=visibleXs(state,autoXEnabled),bad=conflicts(state.crowns);board.innerHTML='';for(const i of allCells){const cell=document.createElement('button'),[r,c]=rc(i);cell.type='button';cell.className=`cell r${regionAt(i)}`;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`Wiersz ${r+1}, kolumna ${c+1}, ${cellState(i,xs)}`);cell.dataset.index=String(i);regionBorders(i,cell);if(bad.has(i))cell.classList.add('bad');if(state.crowns.has(i))cell.innerHTML=crownMarkup;else if(xs.has(i))cell.innerHTML='<span class="mark x-mark" aria-hidden="true">×</span>';cell.addEventListener('click',()=>makeMove(i));cell.addEventListener('keydown',handleCellKeys);board.appendChild(cell)}$('#crownCounter').textContent=`${state.crowns.size}/${N}`;undoBtn.disabled=!history.length||finished;$('#mobileUndo').disabled=!history.length||finished;hintBtn.disabled=finished;$('#mobileHint').disabled=finished;done.classList.toggle('show',finished);updateFeedback(bad)}
function handleCellKeys(e){const index=Number(e.currentTarget.dataset.index);const[r,c]=rc(index);let next=null;if(e.key==='ArrowUp'&&r>0)next=index-N;if(e.key==='ArrowDown'&&r<N-1)next=index+N;if(e.key==='ArrowLeft'&&c>0)next=index-1;if(e.key==='ArrowRight'&&c<N-1)next=index+1;if(next!==null){e.preventDefault();board.children[next]?.focus()}}
function completeDailyIfNeeded(){const today=localDateKey();if(figlo.daily.date!==today)figlo.daily={date:today,requiredGames:['korony'],completedGames:[]};const already=figlo.daily.completedGames.includes('korony');if(!already){figlo.daily.completedGames.push('korony');figlo.user.completedGames+=1}const dayComplete=figlo.daily.requiredGames.every(id=>figlo.daily.completedGames.includes(id));if(dayComplete&&!figlo.history.completedDates.includes(today)){figlo.history.completedDates.push(today);figlo.user.completedDays+=1;const diff=dateDiff(figlo.user.lastCompletedDate,today);figlo.user.streak=diff===1?Math.max(1,figlo.user.streak+1):1;figlo.user.bestStreak=Math.max(figlo.user.bestStreak,figlo.user.streak);figlo.user.lastCompletedDate=today}}
function saveCompletion(ms){const g=figlo.games.korony;const previousBest=g.bestTimeMs;const isRecord=!previousBest||ms<previousBest;if(isRecord)g.bestTimeMs=ms;g.completedCount=(g.completedCount||0)+1;g.totalTimeMs=(g.totalTimeMs||0)+ms;completeDailyIfNeeded();persist();$('#recordBadge').hidden=!isRecord;refreshStats()}
function makeMove(i){if(finished)return;startTimer();clearHint();history.push(snapshot(state));state=cycleCell(state,i,{autoXEnabled});if(isSolved(state)){finished=true;const ms=started?Date.now()-start:0;timer.textContent=fmt(ms);stopTimer();finalTime.textContent=`Czas ${timer.textContent}`;saveCompletion(ms)}render()}
function showHint(){if(finished)return;clearHint();const h=getHint(state,history);if(!h){hintText.textContent='Nie znalazłem teraz prostej, uczciwej dedukcji.';hintCard.classList.add('show');return}for(const i of h.area||[])board.children[i]?.classList.add('hint-area');for(const i of h.focus||[])board.children[i]?.classList.add('hint-focus');for(const i of h.cells||[])board.children[i]?.classList.add(h.kind==='error'?'hint-error':'hint-candidate');for(const i of h.eliminate||[])board.children[i]?.classList.add('hint-eliminate');hintText.innerHTML='<div class="hint-section"><span class="hint-label">Dlaczego</span><p class="hint-copy"></p></div><div class="hint-section"><span class="hint-label">Co zrobić</span><p class="hint-copy"></p></div>';const cp=hintText.querySelectorAll('.hint-copy');cp[0].textContent=h.reason||h.text;cp[1].textContent=h.action||h.text;hintCard.classList.add('show')}
function resetRound(){state=createGameState();history=[];finished=false;started=false;stopTimer();timer.textContent='00:00';finalTime.textContent='';$('#recordBadge').hidden=true;clearHint();render()}
function practiceSeed(){return globalThis.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function undo(){if(!history.length||finished)return;clearHint();const p=history.pop();state=createGameState(p.crowns,p.manualXs);render()}
function setAutoX(value){autoXEnabled=value;autoXInput.checked=value;mobileAutoX.setAttribute('aria-pressed',String(value));figlo.settings.autoX=value;persist();clearHint();render()}
function toggleRules(){const rules=$('#rules');rules.open=!rules.open;if(rules.open)rules.scrollIntoView({behavior:'smooth',block:'nearest'})}

undoBtn.addEventListener('click',undo);$('#mobileUndo').addEventListener('click',undo);$('#reset').addEventListener('click',resetRound);$('#mobileReset').addEventListener('click',resetRound);$('#clearMarks').addEventListener('click',()=>{if(finished||!state.manualXs.size)return;startTimer();clearHint();history.push(snapshot(state));state=clearManualXs(state);render()});hintBtn.addEventListener('click',showHint);$('#mobileHint').addEventListener('click',showHint);$('#hintClose').addEventListener('click',clearHint);$('#rulesBtn').addEventListener('click',toggleRules);$('#helpTop').addEventListener('click',toggleRules);autoXInput.addEventListener('change',()=>setAutoX(autoXInput.checked));mobileAutoX.addEventListener('click',()=>setAutoX(!autoXEnabled));nextPuzzleBtn.addEventListener('click',async()=>{nextPuzzleBtn.disabled=true;nextPuzzleBtn.textContent='Generuję…';await new Promise(r=>requestAnimationFrame(r));try{const p=generatePuzzle(practiceSeed());setRegions(p.regions);practiceNumber++;roundLabel.textContent=`${Math.min(practiceNumber,5)}/5`;resetRound();nextPuzzleBtn.textContent='Dalej: następna plansza →'}catch(e){console.error(e);nextPuzzleBtn.textContent='Spróbuj ponownie'}nextPuzzleBtn.disabled=false});

persist();refreshStats();render();